## https://fluid-dev.github.io/hexo-fluid-docs/guide

# 覆盖配置
about:
  icons:  # 不要把 icon 注释掉，否则无法覆盖配置
    # - { class: 'iconfont icon-github-fill', link: 'https://github.com' }
    # - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }

# 静态资源
static_prefix:
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/

# 页面顶部大图
banner_img: /img/bg/the-starry-night.jpg

# 博客标题
navbar:
  blog_title: 星海旅人

# 导航菜单
# navbar:
#   menu:
#     - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
#     - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
#     - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: '联系我' }
#     - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
#     - {
#         key: '文档',
#         icon: 'iconfont icon-books',
#         submenu: [
#           { key: '主题博客', link: 'https://hexo.fluid-dev.com/' },
#           { key: '配置指南', link: 'https://hexo.fluid-dev.com/docs/guide/' },
#           { key: '图标用法', link: 'https://hexo.fluid-dev.com/docs/icon/' }
#         ]
#       }

# 懒加载
lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2

# 全局字体
font:  # 主题字体配置
  font_size: 16px        # 全局字号
  font_family:           # 全局字体族
  code_font_size: 85%    # 代码的字号

# 网页统计
web_analytics:  # 网页访问统计
  enable: false # 默认为false，启用网页统计改为true即可
  baidu:  # 百度统计的Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
  google:  # Google统计的Tracking ID，参见 https://analytics.google.com/analytics/web/
  tencent:  # 腾讯统计的H5 App id，参见 https://mta.qq.com/h5/manage/ctr_app_manage (开启高级功能才有cid)
    sid:
    cid:
  woyaola:  # 51.la站点统计ID，参见 https://www.51.la/user/site/index
  cnzz:  # 友盟/cnzz站点统计web_id，参见 https://web.umeng.com/main.php?c=site&a=show
  leancloud:  # LeanCloud 计数统计，可用于 PV UV 展示，如果 web_analytics.enable 没有开启，PV UV 展示只会查询，不会增加
    app_id:
    app_key:
    server_url:  # REST API 服务器地址，国际版不填

# 展示 PV 与 UV 统计
footer:
  statistics:
    enable: false
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

# 强制全局 HTTPS
force_https: true

# 二级站点路径
#url: http://xxx.com/blog
#root: /blog/

# 自定义 JS/CSS/HTML
# 指定自定义 js 文件路径，路径是相对 source 目录
#custom_js: /js/custom.js
# 指定自定义 css 文件路径，路径是相对 source 目录
#custom_css:
# - /css/custom.css
# 自定义 <head> 节点中的 HTML 内容
#custom_head: '<meta name="key" content="value">'
# 自定义底部 HTML 内容（位于 footer 上方），也可用于外部引入 js css 这些操作，注意不要和 post.custom 配置冲突
#custom_html: '<link rel="stylesheet" href="//at.alicdn.com/t/font_1067060_qzomjdt8bmp.css">

# 暗色模式
dark_mode:
  enable: true
  default: auto

# Slogan(打字机)
index:
  slogan:
    enable: true
    text: 梦里不觉秋已深，余情岂是为他人
    api:
      enable: true
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

# 文章摘要
#index:
#  auto_excerpt:
#    enable: true

# 文章跳转方式
#index:
#  post_url_target: _self

# 文章信息
# index:
#   post_meta:
#     date: true
#     category: true
#     tag: true

# 文章排序
# index:
#   post_sticky:
#     enable: true
#     icon: 'iconfont icon-top'

# 文章在首页的默认封面图
#post:
#  default_index_img: /img/example.jpg

# 日期/字数/阅读时长/阅读数
post:
  meta:
    author:  # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
      enable: false
    date:  # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
      enable: true
      format: "dddd, MMMM Do YYYY, h:mm a"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: true
      format: "{} 分钟"
    views:  # 阅读次数
      enable: false
      source: "leancloud"  # 统计数据来源，可选：leancloud | busuanzi   注意不蒜子会间歇抽风
      format: "{} 次"

# 代码块
code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: 'Github Gist'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true

# 标签页
tag:
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px  # 字号单位
    start_color: "#BBBBEE"
    end_color: "#337ab7"

# 脚注
# post:
#   footnote:
#     enable: true
#     header: ''

# LaTeX 数学公式
# post:
#   math:
#     enable: false
#     specific: false
#     engine: mathjax

# Mermaid 流程图
# post:
#   mermaid:
#     enable: true
#     specific: false
#     options:

# 关于信息
# about:
#   avatar: /img/avatar.png
#   name: "Fluid"
#   intro: "An elegant theme for Hexo"

# 社交页图标
# about:
#   icons:
#     - { class: 'iconfont icon-github-fill', link: 'https://github.com', tip: 'GitHub' }
#     - { class: 'iconfont icon-douban-fill', link: 'https://douban.com', tip: '豆瓣' }
    # - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }

# 友情链接页
# links:
#   items:
#     - {
#       title: 'Fluid Docs',
#       intro: '主题使用指南',
#       link: 'https://hexo.fluid-dev.com/docs/',
#       avatar: '/img/favicon.png'
#     }
#   default_avatar: /img/avatar.png

# 自定义页面
# page:
#   banner_img: /img/default.png
#   banner_img_height: 70
#   banner_mask_alpha: 0.3
